### ISSUE TITLE
Scheduler stops working after a while

### ISSUE THREAD

**Issue by mwl** [humio/dcos2humio#16]
For some reason the `leader.mesos` cannot be resolved

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://leader.mesos:5050/state": Network is unreachable (connect failed); nested exception is java.net.SocketException: Network is unreachable (connect failed)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:713) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:657) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:346) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at com.humio.mesos.dcos2humio.scheduler.service.FilebeatConfigurationGenerator.updateConfig(FilebeatConfigurationGenerator.java:61) ~[classes!/:na]
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_144]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_144]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_144]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_144]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_144]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_144]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[na:1.8.0_144]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:104) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.boot.actuate.metrics.web.client.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:71) ~[spring-boot-actuator-2.0.0.M5.jar!/:2.0.0.M5]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:92) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:76) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:699) ~[spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	... 15 common frames omitted
```

**Comment by mwl** [comment]
This is just the http client saying that `leader.mesos` is unreachable. Important thing is that it comes back healthy.
